#!/bin/bash
sudo apt update -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
wget https://filestore.fortinet.com/forticlient/forticlient_vpn_7.0.7.0246_amd64.deb
sudo dpkg -i forticlient_vpn_7.0.7.0246_amd64.deb
sudo apt --fix-broken install -y
Sudo apt update --fix-missing -y
wget https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
sudo dpkg -i rustdesk-1.1.9.deb
sudo apt --fix-broken install -y
Sudo apt update --fix-missing -y
wget https://products.s.kaspersky-labs.com/endpoints/keslinux10/11.2.0.4528/multilanguage-11.2.0.4528/3437313131347c44454c7c31/kesl_11.2.0-4528_amd64.deb 
sudo dpkg -i kesl_11.2.0-4528_amd64.deb
sudo /opt/kaspersky/kesl/bin/kesl-setup.pl -y
echo -e '# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
192.168.16.77 actasap.actcorp.in
192.168.16.76 ameyoapp.actcorp.in
192.168.16.80 ameyoart.actcorp.in
192.168.16.54 ameyoout.actcorp.in
192.168.16.53 ameyooutcall.actcorp.in'>>hosts
cp hosts /etc/hosts

