#!/bin/bash
sudo apt update -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
wget https://filestore.fortinet.com/forticlient/forticlient_vpn_7.0.7.0246_amd64.deb
sudo dpkg -i forticlient_vpn_7.0.7.0246_amd64.deb
sudo apt --fix-broken install -y
Sudo apt update --fix-missing -y
wget https://github.com/rustdesk/rustdesk/releases/download/1.1.9/rustdesk-1.1.9.deb
sudo dpkg -i rustdesk-1.1.9.deb

